### PR TITLE
how could your kid have blue eyes

### PR DESCRIPTION
**Pull request by zendern**

### CODE REVIEW

**Review by fitzoh — APPROVED** [review]
This is good... I think we might need to expand on it at some point and ask @dotnetgeekette questions occasionally

**Comment by zendern** [comment]
> ask @DotNetGeekette questions occasionally

huh???

**Comment by tylerrasor** [comment]
so a MIL-bot to ask dumb questions?

**Comment by fitzoh** [comment]
>huh???
```
if user == Jamie && rand(20) {
    message.replyThread("I still don't understand how Matthew has blue eyes")
}
```

**Pull request merged**
